main: de.rexlnico.realtimeplugin.main.Main
authors: [ rexlNico, fluse1367 ]
version: 3.8
api-version: 1.19
name: RealTimePlugin
website: https://rexlNico.de

commands:
  realtime:
    description: The command for plugin usage.
    usage: <Command>